// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

/*
Package org_dakstudios_srv_auth_jwt is a generated protocol buffer package.

It is generated from these files:
	proto/auth/auth.proto

It has these top-level messages:
	Token
	AuthenticateRequest
	AuthenticateResponse
	AuthorizeRequest
	AuthorizeResponse
*/
package org_dakstudios_srv_auth_jwt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Token struct {
	// jwt token
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthenticateRequest struct {
	// user email
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	// user password
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *AuthenticateRequest) Reset()                    { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()               {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthenticateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthenticateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticateResponse struct {
	// jwt token
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *AuthenticateResponse) Reset()                    { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()               {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthenticateResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type AuthorizeRequest struct {
	// jwt token
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	// permission
	Permission string `protobuf:"bytes,2,opt,name=permission" json:"permission,omitempty"`
}

func (m *AuthorizeRequest) Reset()                    { *m = AuthorizeRequest{} }
func (m *AuthorizeRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthorizeRequest) ProtoMessage()               {}
func (*AuthorizeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AuthorizeRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *AuthorizeRequest) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

type AuthorizeResponse struct {
	// true if user authorized for the action
	Authorized bool `protobuf:"varint,1,opt,name=authorized" json:"authorized,omitempty"`
}

func (m *AuthorizeResponse) Reset()                    { *m = AuthorizeResponse{} }
func (m *AuthorizeResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthorizeResponse) ProtoMessage()               {}
func (*AuthorizeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AuthorizeResponse) GetAuthorized() bool {
	if m != nil {
		return m.Authorized
	}
	return false
}

func init() {
	proto.RegisterType((*Token)(nil), "org.dakstudios.srv.auth.jwt.Token")
	proto.RegisterType((*AuthenticateRequest)(nil), "org.dakstudios.srv.auth.jwt.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "org.dakstudios.srv.auth.jwt.AuthenticateResponse")
	proto.RegisterType((*AuthorizeRequest)(nil), "org.dakstudios.srv.auth.jwt.AuthorizeRequest")
	proto.RegisterType((*AuthorizeResponse)(nil), "org.dakstudios.srv.auth.jwt.AuthorizeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for JWT service

type JWTClient interface {
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...client.CallOption) (*AuthenticateResponse, error)
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...client.CallOption) (*AuthorizeResponse, error)
}

type jWTClient struct {
	c           client.Client
	serviceName string
}

func NewJWTClient(serviceName string, c client.Client) JWTClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "org.dakstudios.srv.auth.jwt"
	}
	return &jWTClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *jWTClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...client.CallOption) (*AuthenticateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "JWT.Authenticate", in)
	out := new(AuthenticateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jWTClient) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...client.CallOption) (*AuthorizeResponse, error) {
	req := c.c.NewRequest(c.serviceName, "JWT.Authorize", in)
	out := new(AuthorizeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for JWT service

type JWTHandler interface {
	Authenticate(context.Context, *AuthenticateRequest, *AuthenticateResponse) error
	Authorize(context.Context, *AuthorizeRequest, *AuthorizeResponse) error
}

func RegisterJWTHandler(s server.Server, hdlr JWTHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&JWT{hdlr}, opts...))
}

type JWT struct {
	JWTHandler
}

func (h *JWT) Authenticate(ctx context.Context, in *AuthenticateRequest, out *AuthenticateResponse) error {
	return h.JWTHandler.Authenticate(ctx, in, out)
}

func (h *JWT) Authorize(ctx context.Context, in *AuthorizeRequest, out *AuthorizeResponse) error {
	return h.JWTHandler.Authorize(ctx, in, out)
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x5d, 0xa5, 0xd2, 0x8e, 0x1e, 0x34, 0x56, 0x28, 0x2b, 0x16, 0xc9, 0xc9, 0x8b, 0x51,
	0xdb, 0x8b, 0x57, 0x4f, 0x82, 0x27, 0x59, 0x0a, 0x9e, 0xa3, 0x1b, 0x6c, 0xec, 0x76, 0x67, 0xcd,
	0x4c, 0x2c, 0xf8, 0x93, 0xfd, 0x15, 0xb2, 0x69, 0x77, 0x89, 0x20, 0x55, 0x7b, 0x59, 0xf6, 0xcd,
	0x4c, 0xde, 0xfb, 0x32, 0x04, 0x8e, 0x2b, 0x87, 0x8c, 0x97, 0xda, 0xf3, 0x34, 0x7c, 0x54, 0xd0,
	0xe2, 0x04, 0xdd, 0x8b, 0xca, 0xf5, 0x8c, 0xd8, 0xe7, 0x16, 0x49, 0x91, 0x7b, 0x57, 0xa1, 0xfd,
	0xba, 0x60, 0x79, 0x0a, 0x9d, 0x09, 0xce, 0x4c, 0x29, 0xfa, 0xd0, 0xe1, 0xfa, 0x67, 0x90, 0x9c,
	0x25, 0xe7, 0xbd, 0x6c, 0x29, 0xe4, 0x1d, 0x1c, 0xdd, 0x7a, 0x9e, 0x9a, 0x92, 0xed, 0xb3, 0x66,
	0x93, 0x99, 0x37, 0x6f, 0x88, 0xeb, 0x61, 0x33, 0xd7, 0xb6, 0x68, 0x86, 0x83, 0x10, 0x29, 0x74,
	0x2b, 0x4d, 0xb4, 0x40, 0x97, 0x0f, 0xb6, 0x43, 0xa3, 0xd5, 0xf2, 0x01, 0xfa, 0xdf, 0x8d, 0xa8,
	0xc2, 0x92, 0x8c, 0xb8, 0x89, 0x63, 0xf7, 0x46, 0x52, 0xad, 0x81, 0x55, 0x81, 0xb4, 0x41, 0x2b,
	0xe0, 0xa0, 0x76, 0x44, 0x67, 0x3f, 0x5a, 0xae, 0x8d, 0xdd, 0xc4, 0x10, 0xa0, 0x32, 0x6e, 0x6e,
	0x89, 0x2c, 0x96, 0x2b, 0xfa, 0xa8, 0x22, 0xc7, 0x70, 0x18, 0xa5, 0xad, 0xe0, 0x87, 0x00, 0xba,
	0x29, 0xe6, 0x21, 0xb3, 0x9b, 0x45, 0x95, 0xd1, 0x67, 0x02, 0x3b, 0xf7, 0x8f, 0x13, 0xe1, 0x61,
	0x3f, 0xbe, 0xbc, 0xb8, 0x5a, 0xcb, 0xf5, 0xc3, 0xc2, 0xd3, 0xeb, 0x7f, 0x9c, 0x58, 0xc2, 0xc9,
	0x2d, 0x51, 0x40, 0xaf, 0x65, 0x16, 0x17, 0xbf, 0x3a, 0xc4, 0x9b, 0x4c, 0xd5, 0x5f, 0xc7, 0x9b,
	0xb4, 0xa7, 0xdd, 0xf0, 0xda, 0xc6, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xee, 0x25, 0x21, 0x29,
	0x86, 0x02, 0x00, 0x00,
}
